[package]
name = "onlinecompiler"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.172"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mysql = "26.0"
dotenvy = "0.15"
