[package]
name = "onlinecompiler"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.172"
bcrypt = "0.17"
jsonwebtoken = "9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mysql = "26.0"
dotenvy = "0.15"
uuid = { version = "1.16.0", features = ["v4"] }
