version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  sandbox:
    build:
      context: .
      dockerfile: Dockerfile.sandbox
    container_name: code-sandbox
    restart: unless-stopped
    volumes:
      - ./sandbox:/sandbox
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

volumes:
  mysql_data:

